# Generated by Django 3.2.7 on 2021-10-02 21:54

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=256)),
                ("days_engaged", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
