# Generated by Django 3.2.7 on 2021-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streak",
            name="published",
            field=models.CharField(default="draft", max_length=80),
        ),
    ]
