# Generated by Django 3.2.7 on 2021-10-16 23:38

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_streak_published"),
    ]

    operations = [migrations.RenameModel("Streak", "DayStreakGoal")]
