# Generated by Django 3.2.7 on 2021-10-17 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211016_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfTimePerDayGoal',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=256)),
                ('duration', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneToTenMeasurement',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=256)),
                ('one_to_ten_measurement_type', models.CharField(choices=[('stop', 'Stop'), ('start', 'Start'), ('continue', 'Continue')], max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimesPerDayStreakGoal',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=256)),
                ('times_engaged', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('plural', models.CharField(max_length=80)),
                ('unit_of_measure_type', models.CharField(choices=[('food', 'Food'), ('time', 'Time')], max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='daystreakgoal',
            name='days_engaged',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='daystreakgoal',
            name='published',
            field=models.CharField(choices=[('published', 'Published'), ('qa', 'Q/A'), ('draft', 'Draft')], default='draft', max_length=80),
        ),
        migrations.CreateModel(
            name='ConsumptionPerDayGoal',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=256)),
                ('representation', models.CharField(choices=[('fractions', 'Fractions'), ('decimal', 'Decimal')], default='decimal', max_length=80)),
                ('fraction_whole_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fraction_numerator', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fraction_denominator', models.IntegerField(choices=[(2, 'Half'), (3, 'Third'), (4, 'Quarter'), (8, 'Eighth')], null=True)),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
