# Generated by Django 3.2.7 on 2021-10-17 05:40

from django.db import migrations, models
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211017_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountoftimeperdaygoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amountoftimeperdaygoal',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='amountoftimeperdaygoal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='amountoftimeperdaygoal',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='consumptionperdaygoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumptionperdaygoal',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='consumptionperdaygoal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumptionperdaygoal',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='daystreakgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daystreakgoal',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='daystreakgoal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='daystreakgoal',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='onetotenmeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetotenmeasurement',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='onetotenmeasurement',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onetotenmeasurement',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='timesperdaystreakgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesperdaystreakgoal',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='timesperdaystreakgoal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timesperdaystreakgoal',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='modified_by',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
    ]
